#ifndef PROTOCOLOCOMUNICACION_H_
#define PROTOCOLOCOMUNICACION_H_

typedef enum {PORTYAMA = 9000, PORTMASTER, PORTNODO, PORTFILESYSTEM} puertos;

typedef enum {SOLICITUDJOB=1, PEDIDOREDUCCION, FALLOTRANSFORMACION, FALLOREDLOCAL, REDGLOBAL, FALLOREDGLOBAL, TRANSFORMACIONOK, REPLANIFICACION, SOLICITUDREDUCCIONLOCAL, SOLICITUDREDUCCIONGLOBAL, REDLOCALOK, REDGLOBALOK, SOLICITUDALMACENAMIENTO, ALMACENAMIENTOOK, ERRORALMACENAMIENTO} ConexionesYAMA;
typedef enum {SOLICITUDARCHIVO = 3} ConexionesFileSystem;
typedef enum {TRANSFORMACIONWORKER=1, REDUCLOCAL, REDUCCIONGLOBAL, ALMACENAMIENTO,
	  SOLICITUDARCHIVOWORKER, RECEPCIONARCHIVOWORKER, FILESYSTEMOK, FILESYSTEMERROR,
	  HANDSHAKE} ConexionesWorker;

#endif /* PROTOCOLOCOMUNICACION_H_ */
